### ISSUE TITLE
Task: Create download page for packaged releases

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#1218]
We need to have a place on the new website where user's can download all previously packaged versions.

Perhaps the url should be `/releases/download` or `releases/all/`

#### Tasks

- [x] Create a folder with all previous releases
- [x] Update `postversion.sh` to copy newly packaged releases into that folder
- [x] Create a page `/releases/all/` that offers links to all packaged releases
- [x] Update `/releases/` to have also link to the packaged release for each of the documented releases

**Comment by sprzybylski** [comment]
@mroderick what do you mean by _packaged versions_?
- zipped pkg directory?
- just pkg/sinon.js
- or the whole repo (we could link to gh release in that case https://github.com/sinonjs/sinon/archive/v2.0.0-pre.5.zip)

**Comment by fatso83** [comment]
I am quite sure Morgan refers to the browser bundles; basically [the Download page on the old page](http://sinonjs.org/download/)

**Comment by mroderick** [comment]
> I am quite sure Morgan refers to the browser bundles; basically the Download page on the old page

Exactly

**Comment by fatso83** [comment]
@sprzybylski, did you have a chance to look at this? Thanks for the previous PR, btw 🎂

**Comment by sprzybylski** [comment]
I did, but the new page looks pretty raw. I open a PR, maybe you'll have suggestions.

**Comment by fatso83** [comment]
Closes by #1256
