### ISSUE TITLE
Task: Publish new website

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#1220]
In order to publish the new website to https://sinon.js.org, the tasks listed below need to be completed

**Note: this issue will be used as an umbrella for tracking all the remaining tasks. As such, it is not complete and will be modified as new tasks emerge**

I have enabled GitHub Pages for the `master/docs` and have fixed a couple of minor issues. You can preview the new site at https://sinonjs.github.io/sinon/

Once we are happy with what we have there, we should publish it to https://sinon.js.org

#### Remaining work

- [x] Merge #1216 - A PR to improve documentation for stubs and sandboxes
- [x] Implement #1218 - Download page for packaged releases
- [x] Implement #1219 - Publish `Changelog.txt` on new site

#### Publication tasks

Once the tasks in section above have been completed, these are the tasks needed to actuall publish the site to https://sinon.js.org

- [x] Update `docs/_config.yml` to not use the `baseurl` option (fixed in ba0a0ee3ab3c7f002607dac97e42019511ac8547)
- [x] [Configure GitHub to use custom domain](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/)
- [x] Update DNS entry for `sinonjs.org`

**Comment by mroderick** [comment]
Ping @fatso83 @mantoni @fearphage @jonnyreeves @cjno

It would be great if you would look over the site and point out any mistakes or omissions that are essential to publishing the new site. 

Any ideas that are not essential for publishing the new site should be captured in separate issues and marked as ideas.

**Comment by mantoni** [comment]
I think it looks really good. If the plan is to release the site before Sinon 2, the big "FIXME: Out of date" in the API Documentation page could be removed.
👍🍾✨

**Comment by lucasfcosta** [comment]
Hi everyone!

First of all, thanks for the awesome job you have been doing with Sinon.

Regarding the website, I'd like to point a few improvements that me, as a user, would expect:

* The menu items on the top right corner are to close to each other, which makes it difficult to read them. I think that increasing their margins would make it look much better.
  * The `API Documentation` item, for example, looks like two separate items because the words have the same distance between them as the other items have from each one
* Headers are too close of the text immediately before them. Increasing the top-margin for headers would make it easier to distinguish between the start and end of each section

For now I think that's all. Let me know if you agree and if want these changes and I'll be opening a PR for them.

Thanks 😄

**Comment by mroderick** [comment]
@lucasfcosta thank you for your feedback.

I would love to have contributions to the documentation, especially contributions that makes the site read better.

**Comment by mroderick** [comment]
> I think it looks really good. If the plan is to release the site before Sinon 2, the big "FIXME: Out of date" in the API Documentation page could be removed.

I think we should launch it with Sinon 2, which will then become the active version linked by the "API Documentation" link in the header.

I haven't been tracking Sinon 2 completeness much, so I don't know if it is ready to ship. In any case, I think we should work on bringing the new site to an acceptable state so we can launch it whenever we decide that Sinon 2 is ready.

**Comment by fatso83** [comment]
I feel there is something missing that could answer all the most common questions and misunderstandings. Simply a FAQ with a list of Q&As. I think it could be on the same page as the Howto's, and the answers would of course link to relevant howtos.

Like: 
- How do I stub the `constructor` in an ES2015 class?
- Why does not ES2015 feature work? 
etc

Of course, creating a section without content makes no sense, so one would have to compile a little list first. Makes sense?

**Comment by mroderick** [comment]
We have a couple of issues for new documentation, I think we should add that to the how-to / faq section.

#1120, #1121 

Considering that we don't have documentation for that currently, I don't think that should hold us back from releasing a new site. However, if we can write some content for that section in a few weeks, then we might as well.

**Comment by fatso83** [comment]
@mroderick, I can try to write those two, but I don't think that should hold us back. Go the MVP route and just get the bare essentials out and we can build upon it. I am not totally sure about #1218 and #1219 : did you intend to take on these yourself, or could anyone contribute on those?

**Comment by mroderick** [comment]
> I am not totally sure about #1218 and #1219 : did you intend to take on these yourself, or could anyone contribute on those? I don't know much about Ruby, but I should be able to make something functional if not beautiful 😄

Anyone is welcome to contribute to those!
I was thinking that if I was to do them, I would try to do them with bash/node and tie it in with the preversion and postversion scripts.

**Comment by mroderick** [comment]
The new site is live
